name: Metrics
on:
  schedule: 
    - cron: "0 */12 * * *"   # Corre cada d√≠a cada 12 hrs UTC
  workflow_dispatch:      # Permite correrlo manualmente

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: josesreyes
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Mexico_City
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_stars: yes
