name: Metrics
on:
  schedule:
    - cron: "0 */12 * * *"   # Corre cada 12 horas
  workflow_dispatch:          # Permite correrlo manualmente

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}   # Usa el token autom√°tico de GitHub
          user: josesreyes
          template: terminal                   # Estilo consola retro
          base: header, repositories
          config_timezone: America/Mexico_City
          plugin_languages: yes
          plugin_languages_limit: 10

