name: Metrics
on:
  schedule:
    - cron: "0 */12 * * *"  # Corre cada 12 horas
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: josesreyes
          template: terminal
          base: header, repositories
          config_timezone: America/Mexico_City
          plugin_languages: yes
          plugin_languages_limit: 6
